#!/usr/bin/bash

if [ "$1" == "" ]; then
    git clean -ndfx
elif [ "$1" == "out" ]; then
    git clean -ndfx
elif [ "$1" == "in" ]; then
    git ls-tree -r HEAD
else
    echo "git list only accepts 'in' or 'out'"
    exit 1
fi
