import = [
    "~/.config/alacritty/themes/themes/omni.toml"
]

[window]
opacity = 0.9

[colors.primary]
background = "#191622"
foreground = "#e1e1e6"

[font]
size = 9.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"
